language: node_js
node_js:
  - "iojs-v3.3"
  - "iojs-v3.0"
  - "iojs-v2.5"
  - "iojs-v2.0"
  - "iojs-v1.8"
  - "iojs-v1.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.6"
  - "0.4"
sudo: false
matrix:
  allow_failures:
    - node_js: "iojs-v2.5"
    - node_js: "iojs-v2.0"
    - node_js: "iojs-v1.8"
    - node_js: "iojs-v1.0"
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "0.9"
    - node_js: "0.8"
    - node_js: "0.6"
    - node_js: "0.4"
addons:
  code_climate:
    repo_token: c93da2cf072402fbbe53d73c3b136f50e3d337125b6f4b1c056881adab818d2e
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < etc/lcov.info